### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'event_ndims'

### ISSUE THREAD

**Issue by cdevin** [haarnoja/sac#11]
I followed the installation instructions and ran the example command bwlow and got a Type Error.

 python ./examples/mujoco_all_sac.py --env=swimmer

I had to change import .variants to import variants in mujoco_all_sac.yI think this is fine because I still get variants.__file__ = '[mypath]/sac/examples/variants.py'

Then, I got this type error:

2018-07-05 17:46:10.885203 PDT | Setting seed to 5
using seed 5
WARNING:tensorflow:Variable += will be deprecated. Use variable.assign_add if you want assignment to the variable value or 'x = x + y' if you want a new python Tensor object.
[2018-07-05 17:46:14,736] Variable += will be deprecated. Use variable.assign_add if you want assignment to the variable value or 'x = x + y' if you want a new python Tensor object.
Traceback (most recent call last):
  File "/home/coline/Research2018/affordances/rllab/scripts/run_experiment_lite.py", line 137, in <module>
    run_experiment(sys.argv)
  File "/home/coline/Research2018/affordances/rllab/scripts/run_experiment_lite.py", line 121, in run_experiment
    method_call(variant_data)
  File "./examples/mujoco_all_sac.py", line 137, in run_experiment
    observations_preprocessor=observations_preprocessor)
  File "/home/coline/Research2018/affordances/sac/sac/policies/latent_space_policy.py", line 58, in __init__
    self.build()
  File "/home/coline/Research2018/affordances/sac/sac/policies/latent_space_policy.py", line 122, in build
    event_ndims=self._Da)
  File "/home/coline/Research2018/affordances/sac/sac/distributions/real_nvp_bijector.py", line 280, in __init__
    self.build()
  File "/home/coline/Research2018/affordances/sac/sac/distributions/real_nvp_bijector.py", line 311, in build
    for i in range(1, num_coupling_layers + 1)
  File "/home/coline/Research2018/affordances/sac/sac/distributions/real_nvp_bijector.py", line 311, in <listcomp>
    for i in range(1, num_coupling_layers + 1)
  File "/home/coline/Research2018/affordances/sac/sac/distributions/real_nvp_bijector.py", line 96, in __init__
    name=name)
TypeError: __init__() got an unexpected keyword argument 'event_ndims'

**Comment by cdevin** [comment]
Nevermind, this was a mujoco problem.

**Comment by cdevin** [comment]
Actually, the problem is that tensorflow changed the bijector contructor: see
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/distributions/bijector_impl.py#L491
vs.
https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/ops/distributions/bijector_impl.py#L382

**Comment by haarnoja** [comment]
Thanks for reporting! The environment file now specifies the tensorflow version explicitly.
