### ISSUE TITLE
what is "sandbox"

### ISSUE THREAD

**Issue by zienn** [haarnoja/sac#26]
Traceback (most recent call last):
  File "/home/xtq/sac/examples/mujoco_all_sac.py", line 15, in <module>
    from sac.algos import SAC
  File "/home/xtq/sac/sac/algos/__init__.py", line 2, in <module>
    from .diayn import DIAYN
  File "/home/xtq/sac/sac/algos/diayn.py", line 10, in <module>
    from sac.policies.hierarchical_policy import FixedOptionPolicy
  File "/home/xtq/sac/sac/policies/__init__.py", line 1, in <module>
    from .nn_policy import NNPolicy
  File "/home/xtq/sac/sac/policies/nn_policy.py", line 6, in <module>
    from sandbox.rocky.tf.policies.base import Policy
ImportError: No module named 'sandbox'

**Comment by haarnoja** [comment]
Hi Termset,

it's this one: [https://github.com/rll/rllab/tree/master/sandbox](https://github.com/rll/rllab/tree/master/sandbox). Note that this repo is not actively maintained anymore. I recommend you to use [softlearning](https://github.com/rail-berkeley/softlearning) repo instead, which includes the most up-to-date version of SAC.

**Comment by zienn** [comment]
Thanks!
